let dares = [
  "Show the last DM you sent without context",
  "Call your crush and serenade them.",
  "List three things you like about your crush.",
  "Call someone you're playing with 'mommy' or 'daddy'",
  "Kiss the player you think looks the cutest.",
  "Lick the neck of the person next to you.",
  "Send a text to your crush explaining your favorite movie plot in vivid detail.",
  "Send 5 pleading emojis to the last person you DMed",
  "Send a paragraph to your crush about 3 things you love about them.",
  "Hold hands with the player on your right for 3 minutes.",
  "Show the last text message you have received without context .",
  "Act like a furry to the 5th person in your DM list's DMs",
  "Pair everyone here up into couples.",
  "Call your crush and try to make conversation for a minute.",
  "Tell everyone about your last kiss.",
  "Text your ex and ask them 'How's it going?'.",
  "Write a love poem to the first person in the offline list",
  "Tell your crush you hate them.",
  "Send every curse word you can think of in chat.",
  "Kiss the person who you think is the best friend to you.",
  "Sit in the lap of the person to your left for 3 turns.",
  "Slap your face.",
  "Kiss the person to your left, either on the hand or cheek.",
  "Yell a swear word really loudly",
  "Send your partner a fake breakup message.",
  "Ask someone out of a gender you aren't attracted to.",
  "Text your crush 'I love you'.",
  "Pretend to date someone for a day.",
  "Send the 8th person in your DMs something embarrassing.",
  "Slap the last person who talked besides yourself.",
  'Change your status to "I\'m a furry, deal with it uwu"',
  "Lick someone's hand.",
  "Kiss someone of your same gender.",
  "Do whatever someone else wants for the rest of the day.",
  "Act like an animal for the next minute",
  "Show the group a picture of one person you find very attractive.",
  "Tell the group about your worst experience on a date.",
  "Tell your crush that you like them",
  "Text to your bff 'I kinda have a crush on you wanna go out?' And don't reply to any of their messages.",
  "Change your Discord PFP to whatever the group decides.",
  "Ask someone in this server out on a date.",
  "Sit on one person's lap for two minutes.",
  "Kiss someone for 1 minute.",
  "Curse as badly as you can for 20 seconds.",
  "Rate everyone here 1-10 in terms of looks.",
  "Describe your crush, but don't give it away.",
  "Exchange a clothing item with the player on your right.",
  "Ask your crush who they have a crush on.",
  "Lick the wall.",
  "Rate everyone here 1-10 in terms of personality.",
  "Propose to someone in the group",
  "Tell the last person you texted that you're pregnant/got someone pregnant.",
  "Sit on the lap of the person you like for 5 mins.",
  "Let someone go through your YouTube history and read it out to the group.",
  "Send knee pics to the group.",
  "Tell the 3rd person in your DMs that you love them",
  "Text your crush about how much you like them, but don't reply to them after that.",
  "Send the most furry-like message possible",
  "Tell your crush that you don't love them.",
  "Let someone go through your Amazon purchase history and read it out to the group.",
  "Send the pleading emoji to the 2nd person in your DMs",
];
module.exports = dares;
