let truths = [
  "Who in this room do you most want to see in a bikini?",
  "What’s the craziest thing you’ve done in front of a mirror?",
  "Hot or not: belly button piercings?",
  "Out of everyone here, who would you pick to date if you had to pick someone?",
  "What's the most romantic thing you've ever done?",
  "Worst date you've ever been on?",
  "What's the naughtiest thing you've done in public?",
  "Which relationship do you prefer: a wild, passionate one or a quiet calm one?",
  "What's the creepiest text you've gotten from a stranger?",
  "What's the sketchiest thing you've seen/heard?",
  "Do you have a crush on someone? If so, who?",
  "What was your most embarassing moment?",
  "Whose voice do you like the most?",
  "Have you ever friendzoned someone?",
  "What was your absolute worst bathroom experience?",
  "Would you ever date someone you met online?",
  "What weird thing do you do when nobody else is around?",
  'Who was the first person you said "I love you" to?',
  "Describe your first partner.",
  "What is the most romantic thing that you have ever done?",
  "Who in this room would you be most happy to share a sleeping bag with?",
  "How many people have you kissed?",
  "Have you ever been to jail?",
  "Who here do you want to cuddle with the most?",
  "If you were stranded on an island, who is the one person you would want to be stuck with you?",
  "Have you ever stolen money from your roommate?",
  "What do you look for in a partner?",
  "How far would you go on a first date?",
  "If you could only pick one swear word to use for the rest of your life, what would it be?",
  "Who was your best partner and why?",
  "Who here do you want to kiss the most?",
  "Are you on a dating site? Or have you ever considered signing up?",
  "Did you drink alcohol before you were legal to do so?",
  "What do you like about your ex?",
  "What are your thoughts on furries?",
  "Would you still love your significant other if they gained 100 pounds?",
  "Your longest and best relationship?",
  "What's something that you find cute that you think is underrated?",
  "How much would you do to get your dream partner?",
  "Do you wash your hands after going to the toilet?",
  "What's the craziest thing that you have ever done without your parents knowing?",
  "Have you ever gone out without wearing a bra or underwear?",
  "Have you ever been intimate in a public place?",
  "Who is the sexiest person here?",
  "Who do you miss seeing the most?",
  "Have you ever had a secret relationship? If so, with who?",
  "Who is the most attractive person in the room?",
  "Have you ever gotten arrested or almost gotten arrested?",
  "Have you ever spent your parent's money on alcohol?",
  "Where are you the most ticklish?",
  "Who is your boyfriend/girlfriend/partner?",
  "Do you think you have a chance at love?",
  "What’s something you love to do with your friends that you’d never do in front of your partner?",
  "Have you ever faked being drunk?",
  "Which person in the room do you think gossips the most?",
  "Have you ever considered cheating?",
  "What is your dream wedding?",
  "How many people have you been with?",
  "What is the thing that you shouldn't know but you know entirely about it?",
  "How would you rate yourself on a scale of 1-10?",
  "Would you still love your crush if they gained 100 pounds?",
  "Where are you on the straight-gay spectrum? Be honest!",
  "Have you ever thought of cheating on your partner?",
  "When was the last time you peed yourself?",
  "What is the best party that you've ever been to?",
  "Who was your first crush?",
  "Have you ever done something to intentionally make your ex jealous?",
  "What are some things you don’t understand about the opposite sex?",
  "Would you ever get a tattoo?",
  "What's the closest you've ever come to cheating?",
  "If you had to date anyone here who would it be?",
  "Who would be the best partner here?",
  "Would you let a parent look through your browsing history?",
  "What is something you've never told anyone?",
  "Who's the oldest person you've dated?",
  "Have you ever kissed someone in public",
  "If you could give up happiness to never be sad, would you?",
  "If you had to kiss one person here, who would you pick?",
  "What do you want your parents not to find out about the most?",
  "Who here acts the most desperate?",
  "Have you ever been physically defended by someone?",
  "Have you ever written a fanfiction?",
  "Who from here would you date and why?",
  "What's the most embarrassing thing in your web history?",
  "Who's the hottest person at work or school?",
  "Do you believe in love at first sight?",
  "What's your least favorite feature about yourself?",
  "Which fictional character would you love to marry?",
  "What is the most attractive quality in a partner?",
  "What's something that your parents did to you that you will never do to your kids?",
  "How do you prepare before a date?",
  "What's one trait that you think is super unattractive?",
  "What's your dream gift for Valentine's?",
  "What secret about yourself did you tell someone in confidence and then they told a lot of people?",
  "What kind of person would you want to marry one day?",
  "Have you ever had a crush on two people at the same time?",
  "Have you ever pressed charges on anyone?",
  "Do you like anyone in this group more than a friend?",
  "Have you ever been rejected by someone?",
  "What's your ideal relationship like, and who would you want to have it with?",
  "What's the first letter of your crush's name?",
  "Are you in love or is it just lust?",
  "Who do you simp for?",
  "What is your favorite thing about the opposite gender (or the gender that you are attracted to?)",
  "Do you still have feelings for an ex?",
  "Which Disney character do you think is the hottest?",
  "Do you remember your first crush?",
  "Pick two people that you'd like to see fight and who do you think would win?",
  "What's the stupidest thing you've done for a crush?",
  "Would you see other people if your partner consented?",
  "Have you had your first kiss?",
  "Have you ever done something that you wish you apologized for when you had the chance?",
  "Would you marry your partner?",
  "What's something you find attractive that others may not?",
  "What's the weirdest thing you've done for your partner?",
  "Who is the best looking person you've ever been with?",
  "Would you break up with someone over text?",
  "Have you ever had a missed connection encounter?",
  "What's one habit your partner has that annoys you?",
  "What do you remember most about your first crush?",
  "Who is the best looking person in the room?",
  "Would you let a friend look through your browsing history?",
  "When was the last time you peed your pants?",
  "What is your favorite thing about your partner?",
  "Have you ever had a same-sex crush?",
  "What is the most recent thing that's happened to you that caused you a lot of anxiety?",
  "Do you prefer to be by yourself or with someone else?",
  "Have you ever had a crush on a friend's partner?",
  "What's the worst thing you have ever done?",
  "What's your sexual orientation? (If you're comfortable sharing)",
  "Where did you used to think babies come from?",
  "Are you wearing underwear?",
  "Have you ever cheated?",
  "Who's more attractive, you or your best friend?",
  "What's the biggest number of crushes you've had at one time?",
  "What would you do if you switched genders for a day?",
  "Would you have kids? If so, how many?",
  "Who here is best at flirting?",
  "Have you ever lied to get out of a bad date?",
  "What was your worst kiss?",
  "What was your first kiss like?",
  "Does the thought of kissing the person to your left excite you?",
  "What’s the strangest thing someone would find in your web search history?",
  "What was your funniest first date ever?",
  "What do you have in your room that your parents don't know about?",
  "What do you value most in a relationship?",
  "Have you been in any fights at school?",
  "What is the last letter in the name of your crush?",
  "Do you have a crush on anyone here?",
  "Have you ever accidentally walked in on your parents naked?",
  "Have you ever asked an ex out again?",
  "Who is/was your longest crush?",
  "Have you ever threatened someone other than your family or friends?",
  "Who would you pick to exchange your partner with if you had to choose?",
  "When was the last time you felt truly alive?",
  "Do you currently have a crush on anyone?",
  "How was your first kiss?",
  "If you had to choose, who would you pick to exchange your girlfriend/boyfriend with?",
  "Have you ever been tempted to cheat on someone?",
  "What was the most physically painful experience of your life?",
  "Who's the most attractive person you know?",
  "Have you ever been caught cheating in school?",
  "Describe your worst kiss ever.",
  "What's your story about breaking the law?",
  "Do you have a social media account that you hide?",
  "Do you simp for any fictional characters, and if so, who?",
  "What's the most embarrassing thing that's happened when you asked someone out?",
  "Do you have a crush on anyone?",
  "Have you ever kissed someone without permission?",
  "What do you look for in a potential love interest?",
  "Which two people here would make the best couple?",
  "Would you fly in a plane to date someone?",
  "Do you love your partner?",
  "What's the craziest thing you would do to make a crush like you back?",
  "What is the first letter in the name of your crush?",
  "Do you prefer making a first step in relationship or do you prefer your SO to do it?",
  "How many kids would you like to have?",
  "What is the most romantic thing that has ever been done for you?",
  "What's the most embarrassing thing you've ever looked up?",
  "Have you ever gone on a blind date?",
  "What would you do on the perfect first date?",
  "What is your biggest fear in a relationship?",
  "Have you ever practiced kissing on something/someone?",
  "Are you in an online relationship?",
  "Have you ever asked someone out and got rejected? What happened?",
  "Who here would be the worst person to date?",
  "Have you ever gotten into a physical altercation with anyone?",
  "Which date do you prefer more, breakfast date or dinner date?",
  "What bad thing have you done that no one else has found out about?",
  "Have you ever lied to your partner about being with others before or during your relationship?",
  "Have you ever had a crush on someone here?",
  "What's the most disgusting prank you've ever played?",
  "Would you go behind a friend's back with a crush?",
  "Is it true that you have more than 4 exes?",
  "Have you ever had a crush on a teacher?",
  "How young were you when you started buying your own alcohol? Did you need a fake ID?",
  "How far would you go with someone that you just met?",
  "Why did your last relationship end?",
  "What’s the first thing you’d do if you could inhabit the body of the opposite sex for one hour?",
  "In the group, who do you think fits the dumb role?",
  "Would you ever get on a dating website?",
];
module.exports = truths;
